name: Python CI

on:
  push:
    branches:
      - main
      - dev2

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        

    - name: Run tests
      run: |
        python -m unittest discover -s tests

  on-failure:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create failure branch
      run: |
        git checkout -B failure-branch
        git commit --allow-empty -m "Failure branch for failed tests"
        git push origin failure-branch
